on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
      - run: npm install --include-dev
        name: Install dependencies
      - run: npm run test
        name: Run unit tests
 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node_version: 20
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build code

  build_image:
    runs-on: ubuntu-latest
    needs: ['build', 'test']
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/openlab-aux/infopanel-client:latest